version: '2'
services: 
  oficina:
    image: oficina-docker:aula2-volumes
    build: .
    ports:
     - 5010:5000
    volumes:
     - .:/usr/src
     - aula2-logs:/tmp
    
    container_name: aula-2

volumes:
  aula2-logs:
    external: true
